server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # cache static files (optional nhưng nên có)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}